name: google-timeline-visualizer
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - geopandas
  - shapely
  - folium
  - matplotlib
  - pyproj
  - requests
  - ffmpeg-python
  - ffmpeg
  - tqdm
  - pillow
  - pip
